### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by Psycho611** [allenlol/ySpigot-Issues#3]
```
> [15:22:25 FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_171]
at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_171]
at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:45) ~[ySpigot.jar:git-PaperSpigot-4c7641d1]
at net.minecraft.server.v1_8_R3.MinecraftServer.lambda$run$1(MinecraftServer.java:603) ~[ySpigot.jar:git-PaperSpigot-4c7641d1]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_171]
at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_171]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_171]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_171]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_171]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_171]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.NullPointerException
at net.minecraft.server.v1_8_R3.LoginListener.lambda$login$4(LoginListener.java:91) ~[ySpigot.jar:git-PaperSpigot-4c7641d1]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_171]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_171]
at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) ~[ySpigot.jar:git-PaperSpigot-4c7641d1]
... 8 more
```

**Comment by allenlol** [comment]
Fixed in 1.0.5 - HOTFIX
